######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
QT += gui qml quick
#RESOURCES += main.qrc default.txt
RESOURCES += main.qml default.txt

# Input
SOURCES += main.cpp \
    treeitem.cpp \
    treemodel.cpp

OTHER_FILES += \
    main.qml

HEADERS += \
    treeitem.h \
    treemodel.h
